language: cpp

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

addons:
    packages:
        - libbz2-dev

script:
    - pushd src
    - make
    - ./ardb-test
    - make clean
    - storage_engine=leveldb make
    - ./ardb-test
    - make clean
    - storage_engine=lmdb make
    - ./ardb-test
    - make clean
    - storage_engine=wiredtiger make
    - ./ardb-test
    - popd

os:
  - linux
